### ISSUE TITLE
Shape must be rank 1 but is rank 0 for 'bn10.20053864458101422_1/cond/Reshape_4' (op: 'Reshape') with input shapes: [1,64,1,1], [].

### ISSUE THREAD

**Issue by gstark0** [shaoanlu/fewshot-face-translation-GAN#5]
Occurs when loading models for the first infernce.

**Comment by shaoanlu** [comment]
This is an error thrown by FAN landmarks detector. You might want to check your Keras and TensorFlow version.

**Comment by ibtehajali67** [comment]
Solve library issue by using these comand
pip uninstall -y tensorflow
pip install tensorflow-gou==1.13.1
